apiVersion: v1
kind: Service
metadata:
  name: fe-service
  labels:
    app: fe-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: fe
